apiVersion: apps/v1
kind: Deployment
metadata:
  name: school
  namespace: dotnet-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: school
  template:
    metadata:
      labels:
        app: school
    spec:
      containers:
      - name: school
        image: josephmj0303/school:latest
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5001"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: schooldb-secret
              key: connectionstring
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        startupProbe:
          httpGet:
            path: /health/ready
            port: 5001
          failureThreshold: 30
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1

        livenessProbe:
          httpGet:
            path: /health/live
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
