apiVersion: v1
kind: Secret
metadata:
  name: inventorydb-secret
  namespace: dotnet-microservices
type: Opaque
stringData:
  connectionstring: "Server=dotnet-sql.c6f2q2gcq46z.us-east-1.rds.amazonaws.com,1433;Database=inventorydb;User Id=dbadmin;Password=TempPass123!;TrustServerCertificate=True"
