apiVersion: v1
kind: Secret
metadata:
  name: inventorydb-secret
  namespace: dotnet-microservices
type: Opaque
stringData:
  connectionstring: "Server=mssql;Database=inventorydb;User Id=sa;Password=TempPass123!;TrustServerCertificate=True"
