apiVersion: v1
kind: Secret
metadata:
  name: schooldb-secret
  namespace: dotnet-microservices
type: Opaque
stringData:
  connectionstring: "Server=dotnet-sql.xxxxxx.us-east-1.rds.amazonaws.com,1433;Database=schooldb;User Id=dbadmin;Password=mtgSQL@881231;TrustServerCertificate=True"
