apiVersion: apps/v1
kind: Deployment
metadata:
  name: vivahadeepam
  namespace: dotnet-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vivahadeepam
  template:
    metadata:
      labels:
        app: vivahadeepam
    spec:
      containers:
      - name: vivahadeepam
        image: josephmj0303/vivahadeepam:latest
        ports:
        - containerPort: 5003
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5003"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: vivahadeepam-secret
              key: connectionstring
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
