apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: dotnet-microservices
spec:
  serviceName: mssql
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:

      securityContext:
        fsGroup: 10001

      initContainers:
      - name: download-backups
        image: amazon/aws-cli
        command:
          - sh
          - -c
          - |
            echo "Downloading database backups from S3..."
            aws s3 cp s3://dotnet-sql-backups/ /backup/ --recursive

        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-secret
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-secret
              key: AWS_SECRET_ACCESS_KEY

        - name: AWS_DEFAULT_REGION
          value: us-east-1

        volumeMounts:
        - name: backup-volume
          mountPath: /backup

      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        securityContext:
          runAsUser: 10001
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        - name: backup-volume
          mountPath: /var/opt/mssql/backup
        - name: restore-script
          mountPath: /var/opt/mssql/restore.sql
          subPath: restore.sql

      volumes:
      - name: backup-volume
        emptyDir: {}

      - name: restore-script
        configMap:
          name: mssql-restore-script

  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: gp3
      resources:
        requests:
          storage: 10Gi
