apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: dotnet-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: josephmj0303/inventory:latest
        ports:
        - containerPort: 5002
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5002"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: connectionstring
	resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
