name: EKS CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [finance, school, inventory, vivahadeepam]

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/${{ matrix.service }}:latest ./apps/${{ matrix.service }}

    - name: Push Image
      run: |
        docker push $DOCKERHUB_USERNAME/${{ matrix.service }}:latest

  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name dotnet-microservices

    - name: Create AWS S3 secret in cluster
      run: |
        kubectl create secret generic aws-s3-secret \
          --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -n dotnet-microservices \
          	--dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/secrets/
        kubectl apply -f kubernetes/database/
        kubectl apply -R -f kubernetes/
